make:
	g++ maze.cpp solve.cpp -std=c++1z -o maze -g

clean:
	rm -f maze

dfs:
	./maze -dfs 25 25

bfs:
	./maze -bfs 25 25

dij:
	./maze -dij 25 25

debug:
	g++ maze.cpp solve.cpp -std=c++1z -o maze -g
